### ISSUE TITLE
Crash on 1.20.1 Forge

### ISSUE THREAD

**Issue by Akoto090** [MehVahdJukaar/slotify#3]
# Incompatibility with Curios
Hey, I tried to use the mod but it just crashes on startup with a weird error.
I used Forge 1.20.1 - 47.1.47 and 47.1.3 (both the same problem).
Fun fact, I tried it without curios but the problem still perhapse.
Seems to be a rendering problem or something like this?
[latest.log](https://github.com/MehVahdJukaar/slotify/files/12550290/latest.log)

``could not find any targets matching 'renderBg' in net.minecraft.client.gui.screens.inventory.InventoryScreen``

**Comment by MehVahdJukaar** [comment]
classic mixins working in dev but not outside for some arcane reason

**Comment by Akoto090** [comment]
I think it works now with the update, thank you so much!

**Comment by Akoto090** [comment]
❤️

**Comment by MehVahdJukaar** [comment]
oh awesome!
